[package]
name = "hh-ai-desktop"
version = "3.0.2"
description = "HH Ai desktop shell"
authors = ["HH Ai"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
